# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: >
      sudo apt-get install -y libconfig-dev libjson-c-dev &&
      ./build.sh &&
      ./generate_config.sh
    command: ./run.sh
